apiVersion: apps/v1
kind: Deployment
metadata: 
  name: apigateway-v1
  namespace: douyin
  labels:
    type: douyin
    app: apigateway
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        type: douyin
        app: apigateway
        version: v1
    spec:
      nodeSelector:
        disktype: douyin
      containers:
      - name: apigateway
        image: registry.cn-hangzhou.aliyuncs.com/douyin_micro_demo/apigateway:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: apigateway
  namespace: douyin 
  labels:
    type: douyin
    app: apigateway
spec:
  type: ClusterIP  
  selector:
    app: apigateway
  ports:
  - port: 8080
    name: apigateway
    protocol: TCP