apiVersion: apps/v1
kind: Deployment
metadata: 
  name: favorite-v1
  namespace: douyin
  labels:
    type: douyin
    app: favorite
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favorite
  template:
    metadata:
      labels:
        type: douyin
        app: favorite
        version: v1
    spec:
      nodeSelector:
        disktype: douyin
      containers:
      - name: favorite
        image: registry.cn-hangzhou.aliyuncs.com/douyin_micro_demo/favorite:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service  
metadata:
  name: favorite
  namespace: douyin
  labels:
    type: douyin
    app: favorite
spec:
  type: ClusterIP
  selector:
    app: favorite
  ports:
    - port: 8080
      name: rpc-favorite
      protocol: GRPC 