apiVersion: apps/v1
kind: Deployment
metadata: 
  name: message-v1
  namespace: douyin
  labels:
    type: douyin
    app: message
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        type: douyin
        app: message
        version: v1
    spec:
      nodeSelector:
        disktype: douyin
      containers:
      - name: message
        image: registry.cn-hangzhou.aliyuncs.com/douyin_micro_demo/message:v1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service  
metadata:
  name: message
  namespace: douyin
  labels:
    type: douyin
    app: message
spec:
  type: ClusterIP
  selector:
    app: message
  ports:
    - port: 8080
      name: rpc-message
      protocol: TCP 