apiVersion: apps/v1
kind: Deployment
metadata: 
  name: relation-v1
  namespace: douyin
  labels:
    type: douyin
    app: relation
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: relation
  template:
    metadata:
      labels:
        type: douyin
        app: relation
        version: v1
    spec:
      nodeSelector:
        disktype: douyin
      containers:
      - name: relation
        image: registry.cn-hangzhou.aliyuncs.com/douyin_micro_demo/relation:v1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service  
metadata:
  name: relation
  namespace: douyin
  labels:
    type: douyin
    app: relation
spec:
  type: ClusterIP
  selector:
    app: relation
  ports:
    - port: 8080
      name: rpc-relation
      protocol: TCP 