apiVersion: apps/v1
kind: Deployment
metadata: 
  name: user-v1
  namespace: douyin
  labels:
    type: douyin
    app: user
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        type: douyin
        app: user
        version: v1
    spec:
      nodeSelector:
        disktype: douyin
      containers:
      - name: user
        image: registry.cn-hangzhou.aliyuncs.com/douyin_micro_demo/user:v1
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: user-v2
  namespace: douyin
  labels:
    type: douyin
    app: user
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        type: douyin
        app: user
        version: v2
    spec:
      nodeSelector:
        disktype: douyin
      containers:
      - name: user
        image: registry.cn-hangzhou.aliyuncs.com/douyin_micro_demo/user:v2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service  
metadata:
  name: user
  namespace: douyin
  labels:
    type: douyin
    app: user
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - port: 8080
      name: rpc-user
      protocol: TCP 
