apiVersion: networking.istio.io/v1beta3
kind: Gateway
metadata:
  name: douyin-apigateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 8080
      name: http
      protocol: HTTP
    hosts:
    - "apigateway.douyin.svc.cluster.local"

---
apiVersion: networking.istio.io/v1beta3
kind: VirtualService
metadata:
  name: apigateway
spec:
  hosts:
  - "apigateway.douyin.svc.cluster.local"
  gateways:
  - douyin-apigateway
  http:
  - match:
    - uri:
        prefix: /douyin
    - uri:
        prefix: /static
    route:
    - destination:
        host: apigateway
        port:
          number: 8080