apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: douyin-apigateway
  namespace: douyin
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http2
      protocol: TCP
    hosts:
    - "apigateway.douyin.svc.cluster.local"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apigateway
  namespace: douyin
spec:
  hosts:
  - "apigateway.douyin.svc.cluster.local"
  gateways:
  - douyin-apigateway
  http:
  - match:
    - uri:
        prefix: /douyin
    - uri:
        prefix: /static
    route:
    - destination:
        host: apigateway
        port:
          number: 8080