apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: favorite
  namespace: douyin
spec:
  hosts:
  - "*.favorite.douyin.svc.cluster.local"
  tcp:
  - match:
    - port: 8080
    route:
    - destination:
        host: favorite
        subset: v1
        port:
          number: 8080
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: favorite
  namespace: douyin
spec:
  host: favorite
  subsets:
  - name: v1
    labels:
      version: v1 
