apiVersion: networking.istio.io/v1beta3
kind: Gateway
metadata:
  name: douyin-feed
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 8080
      name: rpc-feed
      protocol: GRPC
    hosts:
    - "feed.douyin.svc.cluster.local"

---
apiVersion: networking.istio.io/v1beta3
kind: VirtualService
metadata:
  name: feed
spec:
  hosts:
  - "feed.douyin.svc.cluster.local"
  gateways:
  - douyin-feed
  grpc:
  - match:
    - port: rpc-feed
    - destination:
        host: feed
        port:
          number: 8080