apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: feed
  namespace: douyin
spec:
  hosts:
  - "*.feed.douyin.svc.cluster.local"
  tcp:
  - match:
    - port: 8080
    route:
    - destination:
        host: feed
        subset: v1
        port:
          number: 8080
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: feed
  namespace: douyin
spec:
  host: feed
  subsets:
  - name: v1
    labels:
      version: v1 
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 10
      http:
        http1MaxPendingRequests: 10
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 5s
      maxEjectionPercent: 100