apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: douyin-mysql
  namespace: douyin
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 3306
      name: mysql
      protocol: TCP
    hosts:
    - "istio-ingressgateway.istio-system.svc.cluster.local"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mysql
  namespace: douyin
spec:
  hosts:
  - "istio-ingressgateway.istio-system.svc.cluster.local"
  gateways:
  - douyin-mysql
  tcp:
  - match:
    - port: 3306
    route:
    - destination:
        host: mysql
        subset: v1
        port: 
          number: 3306
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mysql
  namespace: douyin
spec:
  host: mysql
  subsets:
  - name: v1
    labels:
      version: v1 