apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: relation
  namespace: douyin
spec:
  hosts:
  - "*.relation.douyin.svc.cluster.local"
  tcp:
  - match:
    - port: 8080
    route:
    - destination:
        host: relation
        subset: v1
        port:
          number: 8080
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: relation
  namespace: douyin
spec:
  host: relation
  subsets:
  - name: v1
    labels:
      version: v1 