apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user
  namespace: douyin
spec:
  hosts:
  - "user.douyin.svc.cluster.local"
  tcp:
  - match:
    - port: 8080
    route:
    - destination:
        host: user
        subset:
          - name: v1
            weight: 50
          - name: v2
            weight: 50
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: user
  namespace: douyin
spec:
  host: user
  subsets:
  - name: v1
    labels:
      version: v1 
  - name: v2  
    labels:
      version: v2