apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: douyin-user
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 8080
      name: rpc-user
      protocol: GRPC
    hosts:
    - user

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: user
spec:
  hosts:
  - user
  gateways:
  - douyin-user
  grpc:
  - match:
    - port: rpc-user
    - destination:
        host: user
        port:
          number: 8080