apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: douyin
  labels:
    type: douyin
    app: mysql
    version: v1
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        type: douyin
        app: mysql
        version: v1
    spec:
      nodeSelector:
        disktype: douyin
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "hdbdn"
        volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-pv
        persistentVolumeClaim:
          claimName: mysql-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv
  namespace: douyin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.16.23.144
    path: /home/hdu606/data/nfs/data/douyin/mysql
---
apiVersion: v1
kind: Service
metadata: 
  name: mysql
  namespace: douyin 
  labels:
    type: douyin
    app: mysql
spec:
  type: NodePort  
  ports:
  - port: 3306
    name: tcp
    protocol: TCP
    nodePort: 30306
  selector:
    app: mysql