apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: redis
  namespace: douyin
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        disktype: douyin
      containers:
      - name: redis
        image: redis:5.0
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-pv
          mountPath: /data
      volumes:
      - name: redis-pv
        persistentVolumeClaim:
          claimName: redis-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv
  namespace: douyin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.16.23.144
    path: /home/hdu606/data/nfs/data/douyin/redis
---
apiVersion: v1
kind: Service  
metadata:
  name: redis
  namespace: douyin
spec:
  type: NodePort
  ports:
    - port: 6379
      nodePort: 30379
  selector:
    app: redis
  
