apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: douyin
  labels:
    type: douyin
    app: mysql
    version: v1
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        type: douyin
        app: mysql
        version: v1
    spec:
      nodeSelector:
        disktype: douyin
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "hdbdn"
---
apiVersion: v1
kind: Service
metadata: 
  name: mysql
  namespace: douyin 
  labels:
    type: douyin
    app: mysql
spec:
  type: NodePort  
  ports:
  - port: 3306
    name: tcp
    protocol: TCP
    nodePort: 30306
  selector:
    app: mysql