apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis
  namespace: douyin
  labels:
    type: douyin
    app: redis
    version: v1
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        type: douyin
        app: redis
        version: v1
    spec:
      nodeSelector:
        disktype: douyin
      containers:
      - name: redis
        image: redis:5.0
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service  
metadata:
  name: redis
  namespace: douyin
  labels:
    type: douyin
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      name: redis
      protocol: TCP
  selector:
    app: redis